rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: 2.0.0
    - rvm: 2.4
    - rvm: ruby-head
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_4.2.gemfile

script: bundle exec rspec spec
